pipelines:
  - name: local
    sources:
      - type: file
        name: demo
        charset: gbk
        paths:
          - /home/zhanglei/*.log
        fields:
          topic: "loggie"
    sink:
      type: dev
      printEvents: true
      codec:
        pretty: true
